POST http://localhost:9999/registration
content-type: application/json

{   
    "name":"Gopher",
    "password":"qроoice-cream"
}

###

POST http://localhost:9999/delete/:id
content-type: application/json

{   
    "id":3
}

###

POST http://localhost:9999/chat
content-type: application/json

{   
    "sendler":1,
    "receiver":2,
    "message":"Not bad"
}

###

GET http://localhost:9999/chat?from=1&to=2