
GET http://localhost:9999/account.save_acc?name=Boozoorg&password=NotYourBusiness HTTP/1.1

###

GET http://localhost:9999/account.send_message?from=Boozoorg&to=Boozoorg&message=Не забыть купить хлеб HTTP/1.1

###

GET http://localhost:9999/account.send_message?from=Boozoorg&to=Sherzod&message=hi HTTP/1.1

###

GET http://localhost:9999/account.send_message?from=Sherzod&to=Boozoorg&message=hello HTTP/1.1